const categories=[['Positioning',84,'Clear role direction'],['Headline',71,'Needs sharper keywords'],['About',76,'Good story, weak hook'],['Experience',82,'Strong proof'],['Skills',74,'Add role-specific skills'],['Credibility',69,'More evidence needed'],['Searchability',73,'Improve keyword coverage']];
const plan=[['DAY 1','Define target role & keywords','Set 8–12 keywords around the role you want.'],['DAY 2','Rewrite your headline','Lead with specialty, audience and outcome.'],['DAY 3','Strengthen your About','Make the first 3 lines value-led and specific.'],['DAY 4','Quantify experience','Add measurable outcomes to three bullets.'],['DAY 5','Upgrade skills','Prioritize skills that match your target role.'],['DAY 6','Add credibility','Add projects, certifications or proof points.'],['DAY 7','Re-score your profile','Run the analyzer again and close remaining gaps.']];
const views=[...document.querySelectorAll('.view')], nav=[...document.querySelectorAll('[data-view]')];
function show(view){views.forEach(v=>v.classList.toggle('active-view',v.id===view));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'})}
nav.forEach(n=>n.addEventListener('click',()=>show(n.dataset.view)));
function renderCategories(){document.getElementById('categoryGrid').innerHTML=categories.map(c=>`<article class="category"><div class="card-top"><span>${c[0].toUpperCase()}</span><span>${c[1]>=80?'Strong':c[1]>=70?'Good':'Focus'}</span></div><div class="grade">${c[1]}<span style="font-size:12px;color:#9aa1ae">/100</span></div><p>${c[2]}</p></article>`).join('')}
function renderPlan(){const list=document.getElementById('planList');const saved=JSON.parse(localStorage.getItem('profileRankPlan')||'[]');list.innerHTML=plan.map((p,i)=>`<div class="plan-row"><span class="check ${saved.includes(i)?'done':''}" data-task="${i}">${saved.includes(i)?'✓':''}</span><div><b>${p[1]}</b><small>${p[2]}</small></div><span class="day">${p[0]}</span></div>`).join('');list.querySelectorAll('[data-task]').forEach(el=>el.addEventListener('click',()=>{const i=+el.dataset.task;let s=JSON.parse(localStorage.getItem('profileRankPlan')||'[]');s=s.includes(i)?s.filter(x=>x!==i):[...s,i];localStorage.setItem('profileRankPlan',JSON.stringify(s));renderPlan();toast('Progress updated');}));}
function analyze(text){const t=text.trim();const words=t? t.split(/\s+/).length:0;const lower=t.toLowerCase();const hasHeadline=/senior|manager|director|lead|specialist|analyst|engineer|sales|marketing|product|operations/.test(lower);const hasNumbers=(t.match(/\b\d+(?:\.\d+)?%?|₹\s?\d+[\w,]*|\b\d+\+?\b/g)||[]).length;const hasSkills=/skills|competenc|expertise/.test(lower);const hasAbout=/about|i |i’m|i'm|lead|build|work/.test(lower);const base=Math.min(94,Math.max(42,58+(hasHeadline?8:0)+(hasNumbers?12:0)+(hasSkills?7:0)+(hasAbout?6:0)+(words>100?5:0)));return {score:base,headline:hasHeadline?82:55,about:hasAbout?78:52,experience:hasNumbers?88:61,skills:hasSkills?81:58,keywords:hasHeadline?79:56,words,hasNumbers};}
function showAnalysis(r){const result=document.getElementById('analysisResult');const gaps=[];if(r.headline<70)gaps.push(['Sharpen your headline','State your target function, specialty and outcome in one searchable line.']);if(!r.hasNumbers)gaps.push(['Add quantified proof','Replace responsibility-only bullets with measurable results.']);if(r.about<70)gaps.push(['Strengthen your About','Open with the value you create and the problems you solve.']);if(!gaps.length)gaps.push(['Increase specificity','Add role-specific keywords and two more proof points.']);result.classList.remove('hidden');result.innerHTML=`<div class="result-head"><div><p class="eyebrow">ANALYSIS COMPLETE</p><h2 style="margin:0;font:800 25px Manrope">Your ProfileRank is <span style="color:var(--accent)">${r.score}/100</span></h2><p style="color:var(--muted);font-size:13px">${r.score>=80?'Strong foundation — focus on polish and proof.':r.score>=65?'Good foundation — a few changes can materially improve your profile.':'Your profile has clear opportunities for improvement.'}</p></div><button class="secondary" id="planFromResult">Open action plan</button></div><div class="result-grid"><div class="result-item"><b>${r.headline}</b><small>Headline</small></div><div class="result-item"><b>${r.about}</b><small>About</small></div><div class="result-item"><b>${r.experience}</b><small>Experience</small></div><div class="result-item"><b>${r.skills}</b><small>Skills</small></div></div><p class="eyebrow">TOP RECOMMENDATIONS</p>${gaps.map(g=>`<div class="recommendation"><b>${g[0]}</b><p>${g[1]}</p></div>`).join('')}`;document.getElementById('planFromResult').addEventListener('click',()=>show('plan'));result.scrollIntoView({behavior:'smooth',block:'start'});}
document.getElementById('runAnalysis').addEventListener('click',()=>{const t=document.getElementById('profileInput').value;showAnalysis(analyze(t));toast('Profile analyzed locally');});
document.getElementById('resumeBtn').addEventListener('click',()=>{const t=document.getElementById('resumeInput').value.trim();const result=document.getElementById('resumeResult');if(!t){result.classList.remove('hidden');result.innerHTML='<b>Paste your resume text first.</b>';return}const words=t.split(/\s+/).length,n=(t.match(/\d+(?:\.\d+)?%?/g)||[]).length,score=Math.min(96,Math.max(48,55+(words>150?10:0)+(n>=3?18:n?8:0)+(/experience|skills|education/i.test(t)?10:0)));result.classList.remove('hidden');result.innerHTML=`<div class="result-head"><div><p class="eyebrow">RESUME CHECK</p><h2 style="margin:0;font:800 25px Manrope">Readiness score <span style="color:var(--accent)">${score}/100</span></h2><p style="color:var(--muted);font-size:13px">${n>=3?'Good evidence of measurable impact.':'Add more numbers, outcomes and role-specific proof.'}</p></div></div><div class="recommendation"><b>Next improvement</b><p>${n<3?'Add 3–5 quantified achievements using %, revenue, time, volume or team size.':'Tailor the strongest bullets to the exact role you are targeting.'}</p></div>`;toast('Resume checked locally');});
const ideaPool=[['AUTHORITY','“The KPI I stopped chasing — and what I track instead.”'],['STORY','“The hardest lesson I learned managing a team.”'],['HOW-TO','“My 15-minute weekly operating review.”'],['CASE STUDY','“How we improved a broken process without adding headcount.”'],['OPINION','“Why busy teams are not always productive teams.”'],['PLAYBOOK','“The 5 questions I ask before changing a process.”']];
document.getElementById('ideaBtn').addEventListener('click',()=>{const picks=[...ideaPool].sort(()=>Math.random()-.5).slice(0,3);document.getElementById('contentGrid').innerHTML=picks.map(p=>`<article class="idea-card"><span class="idea-tag">${p[0]}</span><h3>${p[1]}</h3><p>Explain the context, share one practical lesson, and give readers a step they can use this week.</p><div class="idea-foot"><span>3–5 min read</span><button class="text-btn copy-btn">Use idea →</button></div></article>`).join('');bindCopy();toast('Fresh ideas generated');});
function bindCopy(){document.querySelectorAll('.copy-btn').forEach(b=>b.addEventListener('click',()=>{toast('Idea selected — draft it in your editor');}));}function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
document.getElementById('resetData').addEventListener('click',()=>{localStorage.removeItem('profileRankPlan');renderPlan();toast('Demo progress reset')});
renderCategories();renderPlan();bindCopy();
