(function(){
  const $=s=>document.querySelector(s);
  function toast(m){const e=$('#toast');if(e){e.textContent=m;e.classList.add('show');clearTimeout(window.__prt);window.__prt=setTimeout(()=>e.classList.remove('show'),2200)}}
  function validUrl(v){try{const u=new URL(v);return u.hostname==='www.linkedin.com'||u.hostname==='linkedin.com'}catch{return false}}
  function openImporter(){
    if($('#profileUrlModal'))return;
    const m=document.createElement('div');m.id='profileUrlModal';m.innerHTML=`<div class="pr-url-backdrop"><div class="pr-url-card"><button class="pr-url-close" id="prUrlClose">×</button><p class="pr-url-eyebrow">LINKEDIN PROFILE IMPORT</p><h2>Analyze your LinkedIn profile</h2><p class="pr-url-copy">Paste your LinkedIn profile URL. ProfileRank will validate the URL and guide you through a user-authorized import. We never pretend a URL alone contains profile evidence.</p><label>LinkedIn profile URL<input id="prLinkedinUrl" placeholder="https://www.linkedin.com/in/your-name" autocomplete="url"></label><button id="prUrlContinue" class="pr-url-primary">Continue →</button><div class="pr-url-note"><b>Why this step?</b><span>LinkedIn does not permit unauthorized scraping or automated copying of profiles. If direct import isn't available, we'll ask you to paste your profile content instead.</span></div><button id="prUrlManual" class="pr-url-secondary">Paste profile content instead</button></div></div>`;document.body.appendChild(m);
    $('#prUrlClose').onclick=()=>m.remove();$('#prUrlManual').onclick=()=>{m.remove();document.querySelector('#profileInput')?.focus();toast('Paste your LinkedIn profile content below')};
    $('#prUrlContinue').onclick=()=>{const v=$('#prLinkedinUrl').value.trim();if(!validUrl(v)||!/linkedin\.com\/in\//i.test(v))return toast('Enter a valid LinkedIn profile URL');localStorage.setItem('profileRankLinkedinUrl',v);m.remove();showImportState(v)};
  }
  function showImportState(url){
    const e=$('#profileUrlImportState');if(!e)return;
    e.classList.remove('hidden');e.innerHTML=`<div class="pr-import-box"><div><p class="pr-url-eyebrow">PROFILE URL SAVED</p><b>${url.replace(/</g,'&lt;')}</b><p>We validated the profile URL. To keep your analysis evidence-based, ProfileRank needs the profile content supplied through an authorized/user-provided route before scoring it.</p></div><div class="pr-import-actions"><button id="prPasteFromUrl" class="secondary">Paste profile content</button><button id="prClearUrl" class="text-btn">Change URL</button></div></div>`;
    $('#prPasteFromUrl').onclick=()=>document.querySelector('#profileInput')?.focus();$('#prClearUrl').onclick=()=>{localStorage.removeItem('profileRankLinkedinUrl');e.classList.add('hidden');openImporter()};
  }
  window.ProfileRankLinkedIn={openImporter,showImportState};
  document.addEventListener('DOMContentLoaded',()=>{
    const style=document.createElement('style');style.textContent=`#profileUrlModal{position:fixed;inset:0;z-index:200}.pr-url-backdrop{min-height:100%;display:grid;place-items:center;padding:20px;background:rgba(10,25,55,.48);backdrop-filter:blur(8px)}.pr-url-card{position:relative;width:min(560px,100%);background:#fff;border:1px solid #dce5f1;border-radius:22px;padding:30px;box-shadow:0 30px 90px rgba(0,20,60,.25)}.pr-url-close{position:absolute;right:18px;top:14px;border:0;background:#f1f4f8;border-radius:50%;width:34px;height:34px;font-size:22px;cursor:pointer}.pr-url-eyebrow{font-size:10px;letter-spacing:.14em;font-weight:800;color:#1769e8;margin:0 0 9px}.pr-url-card h2{font:800 29px/1.1 Manrope;margin:0 0 10px;color:#10265c}.pr-url-copy{font-size:13px;line-height:1.65;color:#68758a;margin-bottom:22px}.pr-url-card label{display:block;font-size:12px;font-weight:800}.pr-url-card input{display:block;width:100%;box-sizing:border-box;margin-top:8px;padding:13px;border:1px solid #d8e0eb;border-radius:10px;outline:none}.pr-url-primary{width:100%;margin-top:16px;border:0;background:#1769e8;color:#fff;border-radius:10px;padding:13px;font-weight:800;cursor:pointer}.pr-url-secondary{width:100%;margin-top:10px;border:1px solid #dce4ef;background:#fff;color:#29466f;border-radius:10px;padding:12px;font-weight:700;cursor:pointer}.pr-url-note{margin-top:18px;padding:13px;border-radius:12px;background:#f6f9fd;color:#65738a;font-size:11px;line-height:1.55}.pr-url-note b,.pr-url-note span{display:block}.pr-url-note b{color:#243c61;margin-bottom:3px}.pr-import-box{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:18px;border:1px solid #dce5f1;background:#f8fbff;border-radius:14px;margin:18px 0}.pr-import-box b{font-size:13px;word-break:break-all}.pr-import-box p{font-size:12px;color:#68758a;line-height:1.5}.pr-import-actions{display:flex;gap:8px;flex-shrink:0}@media(max-width:650px){.pr-import-box{display:block}.pr-import-actions{margin-top:12px}}`;document.head.appendChild(style);
    const host=document.querySelector('#profileInput')?.closest('.card,.panel,.analyzer-card')||document.querySelector('#profileInput')?.parentElement;
    if(host&&!$('#profileUrlImportState')){const box=document.createElement('div');box.id='profileUrlImportState';box.className='hidden';host.prepend(box)}
    const buttons=[...document.querySelectorAll('[data-linkedin-url],#linkedinUrlBtn,#profileUrlBtn')];buttons.forEach(b=>b.addEventListener('click',openImporter));
    const saved=localStorage.getItem('profileRankLinkedinUrl');if(saved)showImportState(saved);
  });
})();
