const MODEL = process.env.AI_MODEL || 'gpt-4o-mini';
const allowedOrigins = new Set(['https://abhigaur834.github.io','http://localhost:3000','http://localhost:5173','http://localhost:8080']);

function send(req,res,status,body){const origin=req.headers.origin;if(origin&&allowedOrigins.has(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Content-Type','application/json');return res.status(status).json(body)}

function evidence(text){
  const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);
  const metrics=[...new Set(text.match(/(?:\d+(?:\.\d+)?%|₹\s?[\d,]+(?:\.\d+)?|\b\d+(?:\.\d+)?\+?\s*(?:years?|months?|people|agents|members|customers|projects?|accounts?|clients?|reps?|employees?)\b)/gi)||[])];
  const achievements=lines.filter(x=>/\b(increased|improved|reduced|grew|delivered|achieved|generated|saved|built|launched|led|managed|drove|raised|cut|optimized|exceeded|reached)\b/i.test(x)).slice(0,10);
  const leadership=lines.filter(x=>/\b(managed|led|coached|mentored|supervised|team|agents|members|people|employees)\b/i.test(x)).slice(0,6);
  const skills=[...new Set((text.match(/\b(sales|revenue|operations|strategy|leadership|management|analytics|marketing|product|customer experience|process improvement|coaching|recruitment|project management|business development|account management|crm|forecasting)\b/gi)||[]).map(x=>x.toLowerCase()))].slice(0,15);
  return {opening:lines[0]||'',metrics,achievements,leadership,skills,wordCount:text.split(/\s+/).filter(Boolean).length};
}

function fallback(profile,role){
  const e=evidence(profile);const metric=e.metrics.length>0;const proof=e.achievements.length>0;const score=Math.max(40,Math.min(94,55+(metric?13:0)+(e.achievements.length>=3?10:proof?5:0)+(e.skills.length>=4?8:3)+(e.wordCount>=120?5:0)));
  const proofLine=e.achievements[0]||e.leadership[0]||'No specific outcome evidence was found in the supplied profile.';
  return {score,summary:proof?`Your profile shows ${e.skills.slice(0,3).join(', ')||'relevant experience'} and specific evidence such as “${proofLine.slice(0,120)}”. For ${role}, the biggest opportunity is to connect that evidence to business impact rather than add generic career language.`:`Your profile gives a starting point for ${role}, but it contains limited outcome evidence. The biggest improvement is to add truthful scope, results and measurable impact to the work you already describe.`,evidence:{roleSignals:[e.opening].filter(Boolean),achievements:e.achievements,metrics:e.metrics,leadershipSignals:e.leadership,skills:e.skills,missingEvidence:[metric?'':'Verified business metrics',e.achievements.length?'':'Specific achievements'].filter(Boolean)},sections:[
    {name:'Positioning',score:e.opening.toLowerCase().includes(role.toLowerCase())?84:68,reason:`Your opening is “${e.opening.slice(0,110)}”. It should make your ${role} positioning clearer using only experience already present.`,actions:[`Align the opening with ${role} using your existing experience.`,`Keep the positioning specific to your actual function and seniority.`]},
    {name:'Headline',score:e.opening?72:55,reason:`The current opening is “${e.opening.slice(0,110)}”. Your strongest evidence should appear earlier.`,actions:['Lead with your real specialty, scope and strongest verified outcome.','Do not add a metric unless it appears in your profile.']},
    {name:'About',score:e.wordCount>=80?76:58,reason:proof?`Your profile contains evidence such as “${proofLine.slice(0,130)}”. The About should connect that proof to your professional value.`:'Your supplied profile has limited About-style context, making your value proposition difficult to distinguish.',actions:['Open with value demonstrated by your actual experience.','Bring one or two verified achievements into the first half.']},
    {name:'Experience',score:metric?86:62,reason:metric?`You already provide measurable evidence (${e.metrics.slice(0,3).join(', ')}). Connect each number to the action that produced it.`:'Your experience is more responsibility-led than outcome-led. Add verified scale or results where available.',actions:['Turn responsibility statements into action + scope + verified outcome.','Use [metric] only when the actual number is not available yet.']},
    {name:'Searchability',score:Math.min(90,58+e.skills.length*2),reason:`Detected profile language: ${e.skills.slice(0,8).join(', ')||'limited role-specific keywords'}. Concentrate these around the target role.`,actions:[`Prioritize keywords genuinely supported by your experience and relevant to ${role}.`,'Mirror terminology already supported by your work.']}
  ],rewrites:{headline:e.skills.length?`${role} | ${e.skills.slice(0,2).map(x=>x.replace(/\b\w/g,c=>c.toUpperCase())).join(' & ')} | ${e.metrics[0]?`Proven ${e.metrics[0]} impact`:'Team & Business Execution'}`:`${role} | ${e.leadership.length?'Team Leadership':'Business Operations'} | Evidence-led professional`,about:proof?`I’m a ${role} with experience in ${e.skills.slice(0,4).join(', ')||'business execution'}. My background includes ${e.achievements.slice(0,2).join(' ')}${e.metrics.length?` Key evidence includes ${e.metrics.slice(0,3).join(', ')}.`:''} I focus on translating priorities into consistent execution, stronger performance and measurable business outcomes.`:`I’m a ${role} with experience in ${e.skills.slice(0,4).join(', ')||'business execution'}. My profile currently shows responsibilities more clearly than outcomes, so I would position my experience around the work I actually own, the scope I influence and the verified results I have delivered.`,experienceBullets:[e.achievements[0]||`Led the ${role.toLowerCase()} responsibilities described in the profile; add the verified outcome.`,e.leadership[0]?`Leadership evidence already present: ${e.leadership[0]}`:'Owned the responsibilities described and improved execution; add the verified scale or outcome.',e.metrics[0]?`Connect the verified result ${e.metrics[0]} directly to the initiative that produced it.`:'Add a verified metric, volume, timeframe or before/after result to the strongest bullet.']},keywords:[...new Set([role.toLowerCase(),...e.skills])].slice(0,8),actionPlan:['Clarify target-role positioning','Rewrite the headline around real evidence','Strengthen About with proof','Quantify three experience bullets','Prioritize supported target-role skills','Add missing credibility evidence','Re-score after edits'].map((task,i)=>({day:`DAY ${i+1}`,task,why:i===3?'Use only verified numbers, scale or outcomes.':'Build on evidence already present in the supplied profile.'})),provider:'local-evidence-fallback'};
}

const schema={type:'object',additionalProperties:false,properties:{score:{type:'number'},summary:{type:'string'},evidence:{type:'object',additionalProperties:false,properties:{roleSignals:{type:'array',items:{type:'string'}},achievements:{type:'array',items:{type:'string'}},metrics:{type:'array',items:{type:'string'}},leadershipSignals:{type:'array',items:{type:'string'}},skills:{type:'array',items:{type:'string'}},missingEvidence:{type:'array',items:{type:'string'}}},required:['roleSignals','achievements','metrics','leadershipSignals','skills','missingEvidence']},sections:{type:'array',items:{type:'object',additionalProperties:false,properties:{name:{type:'string'},score:{type:'number'},reason:{type:'string'},actions:{type:'array',items:{type:'string'}}},required:['name','score','reason','actions']}},rewrites:{type:'object',additionalProperties:false,properties:{headline:{type:'string'},about:{type:'string'},experienceBullets:{type:'array',items:{type:'string'}}},required:['headline','about','experienceBullets']},keywords:{type:'array',items:{type:'string'}},actionPlan:{type:'array',items:{type:'object',additionalProperties:false,properties:{day:{type:'string'},task:{type:'string'},why:{type:'string'}},required:['day','task','why']}}},required:['score','summary','evidence','sections','rewrites','keywords','actionPlan']};

function prompt(role,profile){return `You are ProfileRank, an evidence-first career intelligence engine. Analyze THIS exact profile for target role ${role}. Do not produce a generic ${role} checklist. First extract evidence, then diagnose gaps, then rewrite. Every recommendation must be traceable to supplied text. Never invent employers, titles, dates, metrics, credentials, tools, responsibilities or achievements. Distinguish responsibilities from achievements. If evidence is missing, call it a gap and use [metric], [scope] or [result] placeholders. Scores must reflect this exact profile and explain why using profile-specific evidence. Rewrites must preserve the user's real career story. Return 5-7 sections, 6-10 keywords and exactly 7 action items.\n\nPROFILE:\n${profile}`}

module.exports=async(req,res)=>{if(req.method==='OPTIONS')return send(req,res,204,{});if(req.method!=='POST')return send(req,res,405,{error:'Method not allowed'});const {role,profile}=req.body||{};const target=(role||'Operations Manager').trim();if(!profile||typeof profile!=='string'||profile.trim().length<30)return send(req,res,400,{error:'Please provide at least 30 characters of profile text.'});if(profile.length>12000)return send(req,res,413,{error:'Profile text is too long. Keep it under 12,000 characters.'});if(!process.env.OPENAI_API_KEY)return send(req,res,200,fallback(profile.trim(),target));try{const response=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,temperature:.15,response_format:{type:'json_schema',json_schema:{name:'profilerank_analysis',strict:true,schema}},messages:[{role:'system',content:'You are an evidence-first career analyst. Personalization and factual grounding matter more than generic polish. Never fabricate.'},{role:'user',content:prompt(target,profile.trim())}]})});const data=await response.json();if(!response.ok)return send(req,res,502,{error:data?.error?.message||'AI provider request failed.'});const content=data?.choices?.[0]?.message?.content;if(!content)return send(req,res,502,{error:'AI provider returned an empty response.'});let result;try{result=JSON.parse(content)}catch{return send(req,res,502,{error:'AI provider returned invalid structured data.'})}return send(req,res,200,{...result,provider:'openai',model:MODEL})}catch(error){console.error('ProfileRank API error:',error);return send(req,res,200,fallback(profile.trim(),target))}};
